### ISSUE TITLE
This polyfill don't work in Safari

### ISSUE THREAD

**Issue by CyrilKrylatov** [idea2app/event-submitter-polyfill#2]
Hi,

Thank you for your polyfill but I'm afraid Safari, our beloved new IE6, won't accept this polyfill.

Indeed, as MDN says [here](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter):

> The read-only submitter property

So in Safari (Version 15.1 (16612.2.9.1.30, 16612)) I have the following issue: 

> TypeError: Attempted to assign to readonly property.

So you can't do this kind of thing I'm afraid: https://github.com/idea2app/event-submitter-polyfill/blob/main/source/index.ts#L42

Furthermore,  this test always returns `true` in Safari: https://github.com/idea2app/event-submitter-polyfill/blob/main/source/index.ts#L31 so Safari don't go after the `return` so the polyfill won't work.

That's not an issue per say, maybe you know how I can we deal with that?

Thank you and take care.

**Comment by TechQuery** [comment]
@CyrilKrylatov @robertfausk I fixed it in 2835c72
