### ISSUE TITLE
the activeElement can be incorrectly set as the submitter

### ISSUE THREAD

**Issue by jenseng** [idea2app/event-submitter-polyfill#6]
This is a bit of an edge case, but the active element should not necessarily be treated as the submitter:

```javascript
const form = document.createElement("form");
document.body.appendChild(form)
const button = document.createElement("button");
form.appendChild(button);

form.addEventListener("submit", (e) => {
  e.preventDefault();
  console.log(e.submitter);
  //  <button></button> 😢 ... should be null
});
button.focus();
form.requestSubmit();
```

Ideally only successfully activated (i.e. clicked) submit buttons should be candidates for being the `submitter`.

**Comment by TechQuery** [comment]
Thank you for catching me up the new API: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit
